### ISSUE TITLE
Incorrect package name

### ISSUE THREAD

**Issue by ghost** [divinenickname/utgen-kotlin-idea-plugin#1]
Hello!

When I'm generating test class your plugin generates incorrect package.
In test class package is correct but in IDE package isn't.

Source code:
```
package org.pkg

class MyAwesome {
    fun yoyo(): Int {
        return 4
    }
}
```

Actual package: `package org.pkg.MyAwesome.kt.org.pkg`
Expected package: `package org.pkg`

Version 1.1.0

**Comment by divinenickname** [comment]
Thanks for issue, this bug was fixed in release 1.2.3
