### ISSUE TITLE
Add .idea folder to gitignore

### ISSUE THREAD

**Issue by divinenickname** [divinenickname/utgen-kotlin-idea-plugin#7]
I forgot to add .idea folder to gitignore

**Comment by Anshu-Bijarnia** [comment]
Hi, i can fix the above issue

**Comment by divinenickname** [comment]
@Anshu-Bijarnia thank you for your interest in the project, I'll wait your PR

**Comment by Anshu-Bijarnia** [comment]
I guess adding .idea/ to gitignore will be sufficient ?

**Comment by divinenickname** [comment]
@Anshu-Bijarnia Yes
